/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Panel;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author erens
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    public static boolean reader = true;
    
    public LoginFrame() {
        initComponents();
       PublicMethods.generalLabel(labelNowUser);
    
        reader = true;
        txtTitle.setText("Reader Login");
    }
    
     public LoginFrame(String adminWriter) {
        initComponents();
        PublicMethods.generalLabel(labelNowUser);
        
        reader = false;
        txtTitle.setText("Writer Login");
        btnSıgnIn.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmail = new javax.swing.JTextField();
        txtTitle = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogIn = new javax.swing.JButton();
        btnSıgnIn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        labelNowUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(710, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEmail.setName(""); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 267, 54));

        txtTitle.setBackground(new java.awt.Color(102, 0, 255));
        txtTitle.setFont(new java.awt.Font("Sylfaen", 1, 48)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(204, 0, 0));
        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitle.setText("Reader Login");
        getContentPane().add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 89, 710, 100));

        labelEmail.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelEmail.setText("E-mail");
        getContentPane().add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 132, 54));

        labelPassword.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelPassword.setText("Password");
        getContentPane().add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 132, 54));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 267, 54));

        btnLogIn.setBackground(new java.awt.Color(0, 0, 0));
        btnLogIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn.setText("Login");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 420, 183, 61));

        btnSıgnIn.setBackground(new java.awt.Color(0, 0, 0));
        btnSıgnIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSıgnIn.setForeground(new java.awt.Color(255, 255, 255));
        btnSıgnIn.setText("Signin");
        btnSıgnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSıgnInActionPerformed(evt);
            }
        });
        getContentPane().add(btnSıgnIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 420, 183, 61));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Adsız.png"))); // NOI18N
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        labelNowUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelNowUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 700, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnSıgnIn() {
        return btnSıgnIn;
    }

    private void btnSıgnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSıgnInActionPerformed
        SigninFrame sıgIn = new SigninFrame();
        
        sıgIn.setVisible(true);
        sıgIn.setLocationRelativeTo(this);
       
        this.dispose();
    }//GEN-LAST:event_btnSıgnInActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        if (reader) {
            String value = PublicMethods.logInController(txtEmail.getText(), new String(txtPassword.getPassword()));

            if (value.equals("writer") || value.equals("admin")) {
                int result = JOptionPane.showOptionDialog(
                        this,
                        "PLEASE GO TO YOUR LOGIN SCREEN.",
                        "WRONG SCREEN",
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE,
                        null,
                        new Object[]{"Okey"},
                        "Okey"
                );
                if (result == 0) {
                    MainFrame mf = new MainFrame();
                    mf.setVisible(true);
                    mf.setLocationRelativeTo(this);
                    this.dispose();
                }
            } else if (value.equals("wrongInputs")) {
                JOptionPane.showMessageDialog(this, "CHECK FIELDS", "Wrong Inputs", JOptionPane.INFORMATION_MESSAGE);
            } else if (value.equals("reader")) {
               
                MainFrame.setEmail(txtEmail.getText());
                MainFrame.setPassword(new String(txtPassword.getPassword()));
                ReaderFrame rf = new ReaderFrame();
                rf.setVisible(true);
                rf.setLocationRelativeTo(this);

                this.dispose();
                
            } else if (value.equals("noPeople")) {
                JOptionPane.showMessageDialog(this, "There is no account with that email", "No Account", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            String value = PublicMethods.logInController(txtEmail.getText(), new String(txtPassword.getPassword()));
            
            if (value.equals("writer")) {
                
                MainFrame.setEmail(txtEmail.getText());
                MainFrame.setPassword(new String(txtPassword.getPassword()));
                
                WriterMainFrame wf = new WriterMainFrame();
                wf.setVisible(true);
                wf.setLocationRelativeTo(this);
                this.dispose();
                
                             
            } else if (value.equals("wrongInputs")) {
             JOptionPane.showMessageDialog(this, "CHECK FIELDS", "Wrong Inputs", JOptionPane.INFORMATION_MESSAGE);

            } else if (value.equals("admin")) {
                
                 MainFrame.setEmail(txtEmail.getText());
                MainFrame.setPassword(new String(txtPassword.getPassword()));
                            
                AdminMainFrame af = new AdminMainFrame();
                af.setVisible(true);
                af.setLocationRelativeTo(this);
                this.dispose();
                         
            } else if (value.equals("reader")){
                 int result = JOptionPane.showOptionDialog(
                        this,
                        "PLEASE GO TO YOUR LOGIN SCREEN.",
                        "WRONG SCREEN",
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE,
                        null,
                        new Object[]{"Tamam"},
                        "Tamam"
                );
                if (result == 0) {
                    MainFrame mf = new MainFrame();
                    mf.setVisible(true);
                    mf.setLocationRelativeTo(this);
                    this.dispose();
                }
            } else if (value.equals("noPeople")) {
                JOptionPane.showMessageDialog(this, "There is no account with that email", "No Account", JOptionPane.INFORMATION_MESSAGE);
            }
        }

  
        
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        PublicMethods.accountClear();
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        mf.setLocationRelativeTo(this);
        
        this.dispose();
        
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnSıgnIn;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNowUser;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
