/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Panel;

import SQL.DatabaseCodes;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author erens
 */
public class SigninFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private static boolean isReader = true;

    public SigninFrame() {
        initComponents();
        check = false;
        PublicMethods.generalLabel(labelNowUser);
        listGenre.addElement("Daily");
        listGenre.addElement("Technology");
        listGenre.addElement("Politic");
        listGenre.addElement("Sport");
        listGenre.addElement("Game");
        listGenre.addElement("Movie/Tv Shows");
        listGenre.addElement("Art");

        comboFavorite.addItem("Daily");
        comboFavorite.addItem("Technology");
        comboFavorite.addItem("Politic");
        comboFavorite.addItem("Sport");
        comboFavorite.addItem("Game");
        comboFavorite.addItem("Movie/Tv Shows");
        comboFavorite.addItem("Art");

        comboFavorite.setVisible(false);
        txtFavorite.setVisible(false);
        textSıgnIn.setText("Reader Register");
        isReader = true;

        listGenres.setModel(listGenre);

        listGenres.setSelectedIndex(0);
    }
    private boolean check = false;

    public SigninFrame(String name) {
        initComponents();
        check = true;
        if (name.equals("writer") && check) {
            PublicMethods.generalLabel(labelNowUser);
            listGenre.addElement("Daily");
            listGenre.addElement("Technology");
            listGenre.addElement("Politic");
            listGenre.addElement("Sport");
            listGenre.addElement("Game");
            listGenre.addElement("Movie/Tv Shows");
            listGenre.addElement("Art");
            textSıgnIn.setText("Writer Register");

            comboFavorite.addItem("Daily");
            comboFavorite.addItem("Technology");
            comboFavorite.addItem("Politic");
            comboFavorite.addItem("Sport");
            comboFavorite.addItem("Game");
            comboFavorite.addItem("Movie/Tv Shows");
            comboFavorite.addItem("Art");

            comboFavorite.setSelectedIndex(0);
            comboFavorite.setVisible(true);
            txtFavorite.setVisible(true);
            isReader = false;
            listGenres.setModel(listGenre);
            listGenres.setSelectedIndex(0);

            comboFavoriteActionPerformed(null);
        }

        if (name.equals("admin") && check) {
            PublicMethods.generalLabel(labelNowUser);
            textSıgnIn.setText("Admin Register");

            labelGenres.setVisible(false);
            jScrollPane1.setVisible(false);

            txtFavorite.setText("Level");
            listGenres.setVisible(false);
            isAdmin = true;
            isReader = false;

            if (AdminFrame.getNowAdmin().getPermissionLevel().equals("0")) {
                comboFavorite.addItem("0");
                comboFavorite.addItem("1");
            } else {
                comboFavorite.addItem("1");
            }

        }

    }
    DefaultListModel listGenre = new DefaultListModel();
    private boolean isAdmin = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtName = new javax.swing.JTextField();
        textSıgnIn = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        labelSurname = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelBiography = new javax.swing.JLabel();
        txtFavorite = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        labelSurnameError = new javax.swing.JLabel();
        labelPasswordError = new javax.swing.JLabel();
        labelNameError = new javax.swing.JLabel();
        labelNowUser = new javax.swing.JLabel();
        labelEmailError = new javax.swing.JLabel();
        labelImageError = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        labelGenderError = new javax.swing.JLabel();
        radioMan = new javax.swing.JRadioButton();
        radioWoman = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listGenres = new javax.swing.JList<>();
        comboFavorite = new javax.swing.JComboBox<>();
        labelGenres = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBiography = new javax.swing.JTextArea();
        labelPassword = new javax.swing.JLabel();
        btnProfilPhoto = new javax.swing.JButton();
        labelGenreError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(710, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtName.setName(""); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 250, 54));

        textSıgnIn.setBackground(new java.awt.Color(102, 0, 255));
        textSıgnIn.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        textSıgnIn.setForeground(new java.awt.Color(204, 0, 0));
        textSıgnIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textSıgnIn.setText("Reader Signin");
        getContentPane().add(textSıgnIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 70));

        labelName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelName.setText("Name");
        getContentPane().add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 71, 54));

        register.setBackground(new java.awt.Color(0, 0, 0));
        register.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 183, 61));

        labelSurname.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelSurname.setText("Surname");
        getContentPane().add(labelSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 101, 54));

        labelEmail.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelEmail.setText("E-mail");
        getContentPane().add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 72, 54));

        labelBiography.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelBiography.setText("Biography");
        getContentPane().add(labelBiography, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 120, 54));

        txtFavorite.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtFavorite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFavorite.setText("Favorite");
        getContentPane().add(txtFavorite, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 100, 60));

        txtSurname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtSurname.setName(""); // NOI18N
        getContentPane().add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 180, 54));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEmail.setName(""); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 248, 54));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 250, 50));

        labelSurnameError.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelSurnameError.setForeground(new java.awt.Color(255, 51, 51));
        labelSurnameError.setText("Fill the area");
        labelSurnameError.setVisible(false);
        getContentPane().add(labelSurnameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));

        labelPasswordError.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelPasswordError.setForeground(new java.awt.Color(255, 51, 51));
        labelPasswordError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPasswordError.setText("Fill the area");
        labelPasswordError.setVisible(false);
        getContentPane().add(labelPasswordError, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 220, 40));

        labelNameError.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelNameError.setForeground(new java.awt.Color(255, 51, 51));
        labelNameError.setText("Fill the area");
        labelNameError.setVisible(false);
        getContentPane().add(labelNameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 130, -1));

        labelNowUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelNowUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 700, 40));

        labelEmailError.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelEmailError.setForeground(new java.awt.Color(255, 51, 51));
        labelEmailError.setText("Email should contains @ .com");
        labelEmailError.setVisible(false);
        getContentPane().add(labelEmailError, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 250, -1));

        labelImageError.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelImageError.setForeground(new java.awt.Color(255, 51, 51));
        labelImageError.setText("Choose photo");
        labelImageError.setVisible(false);
        getContentPane().add(labelImageError, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 150, 40));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Adsız.png"))); // NOI18N
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        labelGenderError.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelGenderError.setForeground(new java.awt.Color(255, 51, 51));
        labelGenderError.setText("Choose gender");
        labelGenderError.setVisible(false);
        getContentPane().add(labelGenderError, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 170, 40));

        buttonGroup1.add(radioMan);
        radioMan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radioMan.setText("Man");
        getContentPane().add(radioMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 40));

        buttonGroup1.add(radioWoman);
        radioWoman.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radioWoman.setText("Woman");
        getContentPane().add(radioWoman, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 40));

        listGenres.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listGenresValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listGenres);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 170, 170));

        comboFavorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFavoriteActionPerformed(evt);
            }
        });
        comboFavorite.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                comboFavoritePropertyChange(evt);
            }
        });
        getContentPane().add(comboFavorite, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 100, -1));

        labelGenres.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelGenres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGenres.setText("Genres");
        getContentPane().add(labelGenres, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 200, 54));

        txtBiography.setColumns(20);
        txtBiography.setRows(5);
        jScrollPane2.setViewportView(txtBiography);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 300, 170));

        labelPassword.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelPassword.setText("Password");
        getContentPane().add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 109, 54));

        btnProfilPhoto.setText("Profil Photo");
        btnProfilPhoto.setMaximumSize(new java.awt.Dimension(67, 16));
        btnProfilPhoto.setMinimumSize(new java.awt.Dimension(67, 16));
        btnProfilPhoto.setPreferredSize(new java.awt.Dimension(67, 16));
        btnProfilPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilPhotoActionPerformed(evt);
            }
        });
        getContentPane().add(btnProfilPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 120, 100));

        labelGenreError.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelGenreError.setForeground(new java.awt.Color(255, 51, 51));
        labelGenreError.setText("Choose genre");
        labelGenreError.setVisible(false);
        getContentPane().add(labelGenreError, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        labelEmailError.setVisible(false);
        labelGenderError.setVisible(false);
        labelImageError.setVisible(false);
        labelNameError.setVisible(false);
        labelPasswordError.setVisible(false);
        labelSurnameError.setVisible(false);
        labelGenreError.setVisible(false);

        String gender = "";
        if (radioMan.isSelected()) {
            gender = "Man";
        } else if (radioWoman.isSelected()) {
            gender = "Woman";
        }
        int selected[] = listGenres.getSelectedIndices();
        ArrayList<String> genres = new ArrayList<>();

        for (int i = 0; i < selected.length; i++) {
            genres.add(listGenre.getElementAt(selected[i]).toString());
        }

        ArrayList<String> sıgnInResult = null;
        if(isAdmin){
            sıgnInResult = PublicMethods.sıgnInController(txtName.getText(), txtSurname.getText(),
                    txtEmail.getText(), new String(txtPassword.getPassword()), genres, isReader, gender,
                    comboFavorite.getSelectedItem().toString(), txtBiography.getText(),
                    DatabaseCodes.convertImageIconToByteArray(profilPhoto), true, comboFavorite.getSelectedItem().toString().trim());
        } else {
            sıgnInResult = PublicMethods.sıgnInController(txtName.getText(), txtSurname.getText(),
                    txtEmail.getText(), new String(txtPassword.getPassword()), genres, isReader, gender,
                    comboFavorite.getSelectedItem().toString(), txtBiography.getText(),
                    DatabaseCodes.convertImageIconToByteArray(profilPhoto), false, null);
        }
        //Error writer
        if (!sıgnInResult.isEmpty()) {
            for (int i = 0; i < sıgnInResult.size(); i++) {
                if (sıgnInResult.get(i).equals("name")) {
                    labelNameError.setVisible(true);
                }
                if (sıgnInResult.get(i).equals("surname")) {
                    labelSurnameError.setVisible(true);
                }
                if (sıgnInResult.get(i).equals("password")) {
                    labelPasswordError.setText("Fill the area");
                    labelPasswordError.setVisible(true);
                }
                if (sıgnInResult.get(i).equals("passwordSize")) {
                    labelPasswordError.setVisible(true);
                    labelPasswordError.setText("Size should above 8");
                }
                if (sıgnInResult.get(i).equals("email")) {
                    labelEmailError.setText("Email should contains @ .com");
                    labelEmailError.setVisible(true);
                }
                if (sıgnInResult.get(i).equals("emailExist")) {
                    labelEmailError.setText("This email already in use.");
                    labelEmailError.setVisible(true);
                }

                if (sıgnInResult.get(i).equals("gender")) {
                    labelGenderError.setVisible(true);
                }
                if (sıgnInResult.get(i).equals("genres")) {
                    labelGenreError.setVisible(true);
                }

                if (sıgnInResult.get(i).equals("image")) {
                    labelImageError.setVisible(true);
                }

            }
        } else {
            if (isReader) {
                LoginFrame logIn = new LoginFrame();
                logIn.setVisible(true);
                logIn.setLocationRelativeTo(this);
            } else if (!isReader && !isAdmin) {
                AdminMainFrame amf = new AdminMainFrame();
                amf.setVisible(true);
                amf.setLocationRelativeTo(this);
            } else if (isAdmin){
                AdminFrame af = new AdminFrame();
                af.setVisible(true);
                af.setLocationRelativeTo(this);
            }
            this.dispose();
        }


    }//GEN-LAST:event_registerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (isReader) {
            PublicMethods.accountClear();
            LoginFrame rf = new LoginFrame();
            rf.setVisible(true);
            rf.setLocationRelativeTo(this);

            this.dispose();
        } else {

            AdminFrame af = new AdminFrame();
            af.setVisible(true);
            af.setLocationRelativeTo(this);
            this.dispose();

        }

    }//GEN-LAST:event_btnBackActionPerformed

    static Object lastSelectedItem = null;
    private void comboFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFavoriteActionPerformed
        if (!isReader) {
            Object selected = comboFavorite.getSelectedItem();

            if (selected == null) {
                return;
            }

            if (lastSelectedItem != null && !listGenre.contains(lastSelectedItem)) {
                listGenre.addElement(lastSelectedItem);
            }
            listGenre.removeElement(selected);
            lastSelectedItem = selected;

            listGenres.setModel(listGenre);

        }

    }//GEN-LAST:event_comboFavoriteActionPerformed

    private void listGenresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listGenresValueChanged
        if (isReader) {
            int indicies[] = listGenres.getSelectedIndices();

            if (indicies.length <= 0) {
                listGenres.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_listGenresValueChanged


    private void comboFavoritePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_comboFavoritePropertyChange

    }//GEN-LAST:event_comboFavoritePropertyChange
    ImageIcon profilPhoto;
    private void btnProfilPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilPhotoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose a visual");
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "Resim Dosyaları", "jpg", "jpeg", "png", "gif", "bmp"
        ));

        int returnValue = fileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            NewsFrame nf = new NewsFrame("size");
            JLabel labelSize = nf.getLabelImageIcon();
            ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());
            if ((imageIcon.getIconHeight() > labelSize.getBounds().height)
                    || (imageIcon.getIconWidth() > labelSize.getBounds().width)) {
                Image scaledImage = imageIcon.getImage().getScaledInstance(
                        labelSize.getWidth(),
                        labelSize.getHeight(),
                        Image.SCALE_SMOOTH
                );
                btnProfilPhoto.setText("");
                btnProfilPhoto.setIcon(new ImageIcon(scaledImage));
                profilPhoto = new ImageIcon(scaledImage);

            } else {
                btnProfilPhoto.setText("");
                btnProfilPhoto.setIcon(imageIcon);
                profilPhoto = imageIcon;
            }

        }
    }//GEN-LAST:event_btnProfilPhotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SigninFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SigninFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SigninFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SigninFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SigninFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProfilPhoto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboFavorite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBiography;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmailError;
    private javax.swing.JLabel labelGenderError;
    private javax.swing.JLabel labelGenreError;
    private javax.swing.JLabel labelGenres;
    private javax.swing.JLabel labelImageError;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNameError;
    private javax.swing.JLabel labelNowUser;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPasswordError;
    private javax.swing.JLabel labelSurname;
    private javax.swing.JLabel labelSurnameError;
    private javax.swing.JList<String> listGenres;
    private javax.swing.JRadioButton radioMan;
    private javax.swing.JRadioButton radioWoman;
    private javax.swing.JButton register;
    private javax.swing.JLabel textSıgnIn;
    private javax.swing.JTextArea txtBiography;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtFavorite;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
