/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NailErenSelimogluDataStructures;

import java.util.ArrayList;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author erens
 */
public class NailErenSelimogluMainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    ArrayList<Object[]> location = new ArrayList<>();
    NailErenSelimogluLinkedList gameList = new NailErenSelimogluLinkedList();
    int count = 0;
    final int[] COL = {14, 74, 134, 194, 254};
    final int[] ROW = {496, 436, 376, 316, 256, 196, 136};
    final int[][] TILE_SEQUENCE = {
        {2,0},{2, 3}, {4, 1}, {2, 2}, {4, 4}, {2, 1}, {4, 4}, {8, 0}, {8, 0}, {32, 1}, {2, 2},
        {64, 2}, {16, 3}, {64, 1}, {32, 2}, {16, 0}, {16, 4}, {32, 2}, {64, 1}, {8, 3}, {4, 3},
        {2, 3}, {2, 3}, {2, 1}, {64, 2}, {32, 2}, {16, 2}, {8, 2}, {8, 2}, {4, 1}, {8, 1}
    };
    final int START_Y = 72;

    public NailErenSelimogluMainScreen() {
        initComponents();
        labelGf.setVisible(false);
        
        int val = TILE_SEQUENCE[0][0];
        int c = TILE_SEQUENCE[0][1];
        int rowPx = ROW[gameList.rowFinder(c)];

        location.add(new Object[]{gameList.add(val, c), COL[c], rowPx});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        btnOnebyOne = new javax.swing.JButton();
        panelArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAnimated = new javax.swing.JButton();
        lable2048 = new javax.swing.JLabel();
        labelGf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Drop Number");
        setBackground(new java.awt.Color(255, 51, 0));
        setFocusableWindowState(false);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setName("frame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMain.setBackground(new java.awt.Color(204, 204, 204));
        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOnebyOne.setBackground(new java.awt.Color(0, 102, 102));
        btnOnebyOne.setFont(new java.awt.Font("Segoe UI Black", 1, 28)); // NOI18N
        btnOnebyOne.setForeground(new java.awt.Color(51, 255, 153));
        btnOnebyOne.setText("One by One");
        btnOnebyOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnebyOneActionPerformed(evt);
            }
        });
        panelMain.add(btnOnebyOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 206, 65));

        panelArea.setBackground(new java.awt.Color(204, 204, 204));
        panelArea.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NailErenSelimogluDataStructures/NailErenSelimogluGridPNG.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        panelArea.add(jLabel1, java.awt.BorderLayout.CENTER);

        panelMain.add(panelArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 306, 426));

        btnAnimated.setBackground(new java.awt.Color(0, 102, 102));
        btnAnimated.setFont(new java.awt.Font("Segoe UI Black", 1, 28)); // NOI18N
        btnAnimated.setForeground(new java.awt.Color(51, 255, 204));
        btnAnimated.setText("Animated");
        btnAnimated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimatedActionPerformed(evt);
            }
        });
        panelMain.add(btnAnimated, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 206, 65));

        lable2048.setBackground(new java.awt.Color(0, 0, 0));
        lable2048.setFont(new java.awt.Font("Segoe UI Black", 0, 45)); // NOI18N
        lable2048.setForeground(new java.awt.Color(102, 102, 102));
        lable2048.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable2048.setText("Drop Number");
        lable2048.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 5));
        panelMain.add(lable2048, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        labelGf.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelGf.setForeground(new java.awt.Color(204, 0, 0));
        labelGf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGf.setText("Game Over");
        labelGf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 10));
        labelGf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelMain.add(labelGf, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 274, 110));

        getContentPane().add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOnebyOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnebyOneActionPerformed

        btnOnebyOne.setEnabled(false);

        Object[] currentData = location.get(count);
        NailErenSelimogluNode node = (NailErenSelimogluNode) currentData[0];
        int value = node.data;
        int x = (int) currentData[1];
        int y = START_Y;
        int targetY = (int) currentData[2];

        JLabel label = new JLabel(String.valueOf(value));
        label.setFont(new Font("Arial", Font.BOLD, 30));
        label.setHorizontalAlignment(SwingConstants.CENTER);

        labelColor(label, value);

        panelMain.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, 54, 54));
        panelMain.setComponentZOrder(label, 0);
        panelMain.revalidate();
        panelMain.repaint();

        Timer timer = new Timer(15, new ActionListener() {
            int currentY = y;
            int speed = 10;

            @Override
            public void actionPerformed(ActionEvent e) {
                if (currentY < targetY) {
                    currentY += speed;
                    if (currentY > targetY) {
                        currentY = targetY;
                    }
                    label.setLocation(x, currentY);
                } else {

                    ((Timer) e.getSource()).stop();

                    panelMain.remove(label);
                    panelMain.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, targetY, 54, 54));

                    panelMain.setComponentZOrder(label, 0);

                    panelMain.revalidate();
                    panelMain.repaint();

                    Timer mergeTimer = new Timer(850, null);
                    mergeTimer.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e2) {

                            if (gameList.merge(gameList) == 1) {
                                ((Timer) e2.getSource()).stop();

                                int absoluteTargetY = ROW[node.row];

                                mergedLabels(label, absoluteTargetY, new Runnable() {
                                    @Override
                                    public void run() {
                                        mergeTimer.start();
                                    }
                                });

                                currentData[2] = absoluteTargetY;

                            } else {
                                ((Timer) e2.getSource()).stop();

                                if (gameList.rowsFilled()) {
                                    labelGf.setVisible(true);
                                    btnAnimated.setEnabled(false);
                                    btnOnebyOne.setEnabled(false);
                                    return;
                                }

                                btnOnebyOne.setEnabled(true);
                                count++;

                                if (count <= TILE_SEQUENCE.length) {
                                    int val = TILE_SEQUENCE[count][0];
                                    int c = TILE_SEQUENCE[count][1];

                                    int rowPx = ROW[gameList.rowFinder(c)];
                                    location.add(new Object[]{gameList.add(val, c), COL[c], rowPx});
                                }

                            }
                        }
                    });

                    mergeTimer.setInitialDelay(0);
                    mergeTimer.start();

                }
            }
        });

        timer.start();


    }//GEN-LAST:event_btnOnebyOneActionPerformed

    private void btnAnimatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimatedActionPerformed
        btnOnebyOne.doClick();
        btnAnimated.setEnabled(false);

        btnOnebyOne.addPropertyChangeListener("enabled", new java.beans.PropertyChangeListener() {
            @Override
            public void propertyChange(java.beans.PropertyChangeEvent evt) {

                if ((boolean) evt.getNewValue() == true) {

                    Timer botTimer = new Timer(400, new java.awt.event.ActionListener() {
                        @Override
                        public void actionPerformed(java.awt.event.ActionEvent e) {
                            if (btnOnebyOne.isEnabled()) {
                                btnOnebyOne.doClick();
                            }
                        }
                    });

                    botTimer.setRepeats(false);
                    botTimer.start();
                }
            }
        });

    }//GEN-LAST:event_btnAnimatedActionPerformed

    private void mergedLabels(JLabel l1, int absoluteTargetY, Runnable onComplete) {
        final int opTime = 6;
        NailErenSelimogluNode node = (NailErenSelimogluNode) location.get(count)[0];
        int value = node.data;
        l1.setText(String.valueOf(value));
        labelColor(l1, value);
        l1.setForeground(new Color(l1.getForeground().getRed(), l1.getForeground().getGreen(), l1.getForeground().getBlue(), 0));
        Timer timer = new Timer(15, new ActionListener() {
            int alpha = 0;
            int currentY = l1.getY();
            int speed = 5;

            @Override
            public void actionPerformed(ActionEvent e) {

                alpha += opTime;
                if (alpha > 255) {
                    alpha = 255;
                }

                if (currentY < absoluteTargetY) {
                    currentY += speed;
                    if (currentY > absoluteTargetY) {
                        currentY = absoluteTargetY;
                    }
                    l1.setLocation(l1.getX(), currentY);
                }

                l1.setForeground(new Color(255, 255, 255, alpha));

                if (alpha >= 255 && currentY >= absoluteTargetY) {
                    ((Timer) e.getSource()).stop();

                    Component[] components = panelMain.getComponents();
                    Rectangle targetArea = new Rectangle(l1.getX(), absoluteTargetY, 54, 54);

                    for (Component comp : components) {
                        if (comp instanceof JLabel && comp != l1) {
                            if (targetArea.intersects(comp.getBounds())) {
                                comp.setVisible(false);
                                panelMain.remove(comp);
                            }
                        }
                    }

                    panelMain.remove(l1);
                    panelMain.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(l1.getX(), absoluteTargetY, 54, 54));
                    panelMain.setComponentZOrder(l1, 0);

                    panelMain.revalidate();
                    panelMain.repaint();

                    Timer pauseTimer = new Timer(100, new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent evt) {

                            if (onComplete != null) {
                                onComplete.run();
                            }
                        }
                    });

                    pauseTimer.setRepeats(false);
                    pauseTimer.start();
                }
            }
        });

        timer.start();
    }

    private void labelColor(JLabel label, int value) {
        int level = 0;
        int temp = value;

        while (temp > 1) {
            temp = temp / 2;
            level++;
        }

        float hue = (level * 0.12f) % 1.0f;
        float saturation = 0.85f;
        float brightness = 0.95f;

        Color vibrantColor = Color.getHSBColor(hue, saturation, brightness);

        label.setOpaque(true);
        label.setBackground(vibrantColor);

        label.setForeground(Color.WHITE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Sistemin kendi orijinal görünümünü yükle (Windows'ta Windows, Mac'te Mac)
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NailErenSelimogluMainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimated;
    private javax.swing.JButton btnOnebyOne;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelGf;
    private javax.swing.JLabel lable2048;
    private javax.swing.JPanel panelArea;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
