/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datastructures;

import dsClasses.*;

/**
 *
 * @author erens
 */
public class RecommendationEngineGUI extends javax.swing.JFrame {

    /**
     * Creates new form RecommendationEngineGUI
     */
    private RecommendationEngine engine;
    private MyLinkedList<User> mainUsers;
    private MyLinkedList<User> targetUsers;
    private javax.swing.JComboBox[] movieCombos;
    private boolean lock = true;

    public RecommendationEngineGUI() {

        initComponents();
        this.movieCombos = new javax.swing.JComboBox[]{comboMovie1, comboMovie2, comboMovie3, comboMovie4, comboMovie5};

        loadDataAndPopulateUI();

        for (int i = 0; i < movieCombos.length; i++) {
            if (movieCombos[i].getItemCount() > i) {
                movieCombos[i].setSelectedIndex(i);
                movieCombos[i].putClientProperty("lastValidIndex", i);
            }
        }

        lock = false;

    }

    private void loadDataAndPopulateUI() {
        mainUsers = FileLoader.loadUsers("src\\datastructures\\main_data.csv");
        targetUsers = FileLoader.loadTargetUsers("src\\datastructures\\target_user.csv");

        engine = new RecommendationEngine(mainUsers);
        engine.loadMovies("src\\datastructures\\movies.csv");

        comboTargetUser.removeAllItems();
        Node<User> currTarget = targetUsers.getHead();
        while (currTarget != null) {
            comboTargetUser.addItem(String.valueOf(currTarget.data.getUserId()));
            currTarget = currTarget.next;
        }

        MyLinkedList<Movie> randomMovies = engine.getRandomMovies(10);
        javax.swing.JComboBox[] movieCombos = {comboMovie1, comboMovie2, comboMovie3, comboMovie4, comboMovie5};

        for (int i = 0; i < movieCombos.length; i++) {
            movieCombos[i].removeAllItems();
            Node<Movie> currMovie = randomMovies.getHead();
            while (currMovie != null) {
                movieCombos[i].addItem(currMovie.data.getId() + " - " + currMovie.data.getName());
                currMovie = currMovie.next;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelByTargetUser = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelTargetUser = new javax.swing.JLabel();
        labelMovieNumberUser = new javax.swing.JLabel();
        labelUserNumberUser = new javax.swing.JLabel();
        comboTargetUser = new javax.swing.JComboBox<>();
        txtUserNumberUser = new javax.swing.JTextField();
        txtMovieNumberUser = new javax.swing.JTextField();
        btnGetRecommendationsUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultsUser = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        panelByCustomRating = new javax.swing.JPanel();
        labelTitle1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultsRating = new javax.swing.JTextArea();
        comboMovie1 = new javax.swing.JComboBox<>();
        comboMovie2 = new javax.swing.JComboBox<>();
        comboMovie3 = new javax.swing.JComboBox<>();
        comboMovie4 = new javax.swing.JComboBox<>();
        comboMovie5 = new javax.swing.JComboBox<>();
        txtRating1 = new javax.swing.JTextField();
        txtRating2 = new javax.swing.JTextField();
        txtRating3 = new javax.swing.JTextField();
        txtRating4 = new javax.swing.JTextField();
        txtRating5 = new javax.swing.JTextField();
        labelUserNumberRating = new javax.swing.JLabel();
        labelMovieNumberRating = new javax.swing.JLabel();
        txtUserNumberRating = new javax.swing.JTextField();
        txtMovieNumberRating = new javax.swing.JTextField();
        btnGetRecommendationsRating = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelByTargetUser.setBackground(new java.awt.Color(204, 204, 204));
        panelByTargetUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setBackground(new java.awt.Color(255, 255, 255));
        labelTitle.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("Target User");
        panelByTargetUser.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 50));

        labelTargetUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTargetUser.setText("Target User");
        panelByTargetUser.add(labelTargetUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, 40));

        labelMovieNumberUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelMovieNumberUser.setText("Movie Number");
        panelByTargetUser.add(labelMovieNumberUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, 30));

        labelUserNumberUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelUserNumberUser.setText("User Number");
        panelByTargetUser.add(labelUserNumberUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, 30));

        comboTargetUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelByTargetUser.add(comboTargetUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 100, 20));

        txtUserNumberUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNumberUserKeyReleased(evt);
            }
        });
        panelByTargetUser.add(txtUserNumberUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 100, 30));

        txtMovieNumberUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMovieNumberUserKeyReleased(evt);
            }
        });
        panelByTargetUser.add(txtMovieNumberUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 100, 30));

        btnGetRecommendationsUser.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnGetRecommendationsUser.setText("Get Recommendetion");
        btnGetRecommendationsUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetRecommendationsUserActionPerformed(evt);
            }
        });
        panelByTargetUser.add(btnGetRecommendationsUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 300, 40));

        txtResultsUser.setEditable(false);
        txtResultsUser.setColumns(10);
        txtResultsUser.setRows(5);
        jScrollPane1.setViewportView(txtResultsUser);

        panelByTargetUser.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 300, 310));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        panelByTargetUser.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 10, 600));

        panelByCustomRating.setBackground(new java.awt.Color(204, 204, 204));
        panelByCustomRating.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        labelTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle1.setText("Custom Rating");
        panelByCustomRating.add(labelTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 50));

        txtResultsRating.setEditable(false);
        txtResultsRating.setColumns(10);
        txtResultsRating.setRows(5);
        jScrollPane2.setViewportView(txtResultsRating);

        panelByCustomRating.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 320, 150));

        comboMovie1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMovie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMovie1ActionPerformed(evt);
            }
        });
        panelByCustomRating.add(comboMovie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 230, -1));

        comboMovie2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMovie2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMovie2ActionPerformed(evt);
            }
        });
        panelByCustomRating.add(comboMovie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 230, -1));

        comboMovie3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMovie3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMovie3ActionPerformed(evt);
            }
        });
        panelByCustomRating.add(comboMovie3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 230, -1));

        comboMovie4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMovie4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMovie4ActionPerformed(evt);
            }
        });
        panelByCustomRating.add(comboMovie4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 230, -1));

        comboMovie5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMovie5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMovie5ActionPerformed(evt);
            }
        });
        panelByCustomRating.add(comboMovie5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 230, -1));

        txtRating1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRating1KeyReleased(evt);
            }
        });
        panelByCustomRating.add(txtRating1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 70, -1));

        txtRating2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRating2KeyReleased(evt);
            }
        });
        panelByCustomRating.add(txtRating2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 70, -1));

        txtRating3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRating3KeyReleased(evt);
            }
        });
        panelByCustomRating.add(txtRating3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 70, -1));

        txtRating4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRating4KeyReleased(evt);
            }
        });
        panelByCustomRating.add(txtRating4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 70, -1));

        txtRating5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRating5KeyReleased(evt);
            }
        });
        panelByCustomRating.add(txtRating5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 70, -1));

        labelUserNumberRating.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelUserNumberRating.setText("User Number");
        panelByCustomRating.add(labelUserNumberRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 170, 30));

        labelMovieNumberRating.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelMovieNumberRating.setText("Movie Number");
        panelByCustomRating.add(labelMovieNumberRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 170, 30));

        txtUserNumberRating.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNumberRatingKeyReleased(evt);
            }
        });
        panelByCustomRating.add(txtUserNumberRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 100, 30));

        txtMovieNumberRating.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMovieNumberRatingKeyReleased(evt);
            }
        });
        panelByCustomRating.add(txtMovieNumberRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 100, 30));

        btnGetRecommendationsRating.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnGetRecommendationsRating.setText("Get Recommendetion");
        btnGetRecommendationsRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetRecommendationsRatingActionPerformed(evt);
            }
        });
        panelByCustomRating.add(btnGetRecommendationsRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 320, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelByTargetUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelByCustomRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelByTargetUser, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelByCustomRating, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetRecommendationsUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetRecommendationsUserActionPerformed
        try {

            int userCount = Integer.valueOf(txtUserNumberUser.getText().trim());
            int movieCount = Integer.valueOf(txtMovieNumberUser.getText().trim());
            int targetNodeId = Integer.valueOf(comboTargetUser.getSelectedItem().toString());

            MyLinkedList<String> results = engine.getUserRecommendation(mainUsers, targetUsers, targetNodeId, userCount, movieCount);

            StringBuilder sb = new StringBuilder();

            if (results.getHead() == null) {
                sb.append("There is no advice for this user, change the user or\n increase the user or movie number");
            } else {
                int count = 1;
                Node<String> curr = results.getHead();
                while (curr != null) {
                    sb.append(count).append(" - ").append(curr.data).append("\n");
                    curr = curr.next;
                    count++;
                }
            }

            txtResultsUser.setText(sb.toString());

        } catch (NumberFormatException e) {
            txtResultsUser.setText("Enter valid numbers.");
        }


    }//GEN-LAST:event_btnGetRecommendationsUserActionPerformed

    private void btnGetRecommendationsRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetRecommendationsRatingActionPerformed

        try {

            if (txtUserNumberRating.getText().trim().isEmpty() || txtMovieNumberRating.getText().trim().isEmpty()) {
                txtResultsRating.setText("Enter valid numbers.");
                return;
            }

            int userCount = Integer.valueOf(txtUserNumberRating.getText().trim());
            int movieCount = Integer.valueOf(txtMovieNumberRating.getText().trim());

            MyLinkedList<Integer> votedMovieIds = new MyLinkedList<>();
            MyLinkedList<Integer> votedRatings = new MyLinkedList<>();

            javax.swing.JComboBox[] movieCombos = {comboMovie1, comboMovie2, comboMovie3, comboMovie4, comboMovie5};
            javax.swing.JTextField[] ratingFields = {txtRating1, txtRating2, txtRating3, txtRating4, txtRating5};

            for (int i = 0; i < 5; i++) {
                if (ratingFields[i].getText().trim().isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(null,
                            "Please enter all ratings first.",
                            "Warning",
                            javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }

            for (int i = 0; i < 5; i++) {
                String ratingStr = ratingFields[i].getText().trim();

                if (!ratingStr.isEmpty()) {
                    int rating = Integer.parseInt(ratingStr);

                    if (rating >= 1 && rating <= 5) {
                        String selectedMovieInfo = movieCombos[i].getSelectedItem().toString();
                        int movieId = Integer.parseInt(selectedMovieInfo.split(" - ")[0].trim());

                        votedMovieIds.add(movieId);
                        votedRatings.add(rating);
                    }
                }
            }

            MyLinkedList<String> results = RecommendationEngine.getCustomRatingRecommendation(mainUsers, votedMovieIds, votedRatings, userCount, movieCount);

            StringBuilder sb = new StringBuilder();

            if (results.getHead() == null) {
                sb.append("There is no advice for this points, change the points or\n increase the user or movie number");
            } else {
                int count = 1;
                Node<String> curr = results.getHead();
                while (curr != null) {
                    sb.append(count).append(" - ").append(curr.data).append("\n");
                    curr = curr.next;
                    count++;
                }
            }

            txtResultsRating.setText(sb.toString());

        } catch (NumberFormatException e) {
            txtResultsRating.setText("Enter valid numbers.");
        }


    }//GEN-LAST:event_btnGetRecommendationsRatingActionPerformed

    private void comboMovie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMovie1ActionPerformed
        controlCombo();
    }//GEN-LAST:event_comboMovie1ActionPerformed

    private void comboMovie2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMovie2ActionPerformed
        controlCombo();
    }//GEN-LAST:event_comboMovie2ActionPerformed

    private void comboMovie3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMovie3ActionPerformed
        controlCombo();
    }//GEN-LAST:event_comboMovie3ActionPerformed

    private void comboMovie4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMovie4ActionPerformed
        controlCombo();
    }//GEN-LAST:event_comboMovie4ActionPerformed

    private void comboMovie5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMovie5ActionPerformed
        controlCombo();
    }//GEN-LAST:event_comboMovie5ActionPerformed

    private void txtRating1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRating1KeyReleased
        controlRatingTxt(txtRating1.getText().trim(), txtRating1);
    }//GEN-LAST:event_txtRating1KeyReleased

    private void txtRating2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRating2KeyReleased
        controlRatingTxt(txtRating2.getText().trim(), txtRating2);
    }//GEN-LAST:event_txtRating2KeyReleased

    private void txtRating3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRating3KeyReleased
        controlRatingTxt(txtRating3.getText().trim(), txtRating3);
    }//GEN-LAST:event_txtRating3KeyReleased

    private void txtRating4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRating4KeyReleased
        controlRatingTxt(txtRating4.getText().trim(), txtRating4);
    }//GEN-LAST:event_txtRating4KeyReleased

    private void txtRating5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRating5KeyReleased
        controlRatingTxt(txtRating5.getText().trim(), txtRating5);
    }//GEN-LAST:event_txtRating5KeyReleased

    private void txtUserNumberUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNumberUserKeyReleased
        controlTxts(txtUserNumberUser.getText().trim(), txtUserNumberUser);
    }//GEN-LAST:event_txtUserNumberUserKeyReleased

    private void txtMovieNumberUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMovieNumberUserKeyReleased
        controlTxts(txtMovieNumberUser.getText().trim(), txtMovieNumberUser);
    }//GEN-LAST:event_txtMovieNumberUserKeyReleased

    private void txtUserNumberRatingKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNumberRatingKeyReleased
        controlTxts(txtUserNumberRating.getText().trim(), txtUserNumberRating);
    }//GEN-LAST:event_txtUserNumberRatingKeyReleased

    private void txtMovieNumberRatingKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMovieNumberRatingKeyReleased
        controlTxts(txtMovieNumberRating.getText().trim(), txtMovieNumberRating);
    }//GEN-LAST:event_txtMovieNumberRatingKeyReleased

    private void controlCombo() {
        if (lock) {
            return;
        }
        for (int i = 0; i < movieCombos.length; i++) {
            final javax.swing.JComboBox currentCombo = movieCombos[i];

            Object selected = currentCombo.getSelectedItem();
            if (selected == null) {
                return;
            }

            boolean isDuplicate = false;

            for (javax.swing.JComboBox otherCombo : movieCombos) {
                if (otherCombo != currentCombo && selected.equals(otherCombo.getSelectedItem())) {
                    isDuplicate = true;
                    break;
                }
            }

            if (isDuplicate) {
                javax.swing.JOptionPane.showMessageDialog(null,
                        "You have already chosen this!\nPlease choose different movie.",
                        "Same movie cannot be selected",
                        javax.swing.JOptionPane.WARNING_MESSAGE);

                int lastValid = (int) currentCombo.getClientProperty("lastValidIndex");
                currentCombo.setSelectedIndex(lastValid);

            } else {
                currentCombo.putClientProperty("lastValidIndex", currentCombo.getSelectedIndex());
            }
        }
    }

    private void controlRatingTxt(String text, javax.swing.JTextField txtField) {

        if (text.isEmpty()) {
            return;
        }

        try {
            int ratingValue = Integer.valueOf(text);

            if (ratingValue < 1 || ratingValue > 5) {
                javax.swing.JOptionPane.showMessageDialog(null,
                        "Enter number between 1 - 5 !",
                        "Invalid number",
                        javax.swing.JOptionPane.ERROR_MESSAGE);

                txtField.setText("");
            }
        } catch (NumberFormatException e) {
            txtField.setText("");
        }
    }

    private void controlTxts(String text, javax.swing.JTextField txtField) {
        if (text.isEmpty()) {
            return;
        }

        if (text.charAt(0) == '0') {
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Number cannot start with 0!",
                    "Invalid Input",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            txtField.setText("");
            return;
        }

        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);

            if (c < '0' || c > '9') {
                javax.swing.JOptionPane.showMessageDialog(null,
                        "Please enter numbers only!",
                        "Invalid Input",
                        javax.swing.JOptionPane.ERROR_MESSAGE);

                txtField.setText("");
                break;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecommendationEngineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecommendationEngineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecommendationEngineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecommendationEngineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecommendationEngineGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetRecommendationsRating;
    private javax.swing.JButton btnGetRecommendationsUser;
    private javax.swing.JComboBox<String> comboMovie1;
    private javax.swing.JComboBox<String> comboMovie2;
    private javax.swing.JComboBox<String> comboMovie3;
    private javax.swing.JComboBox<String> comboMovie4;
    private javax.swing.JComboBox<String> comboMovie5;
    private javax.swing.JComboBox<String> comboTargetUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelMovieNumberRating;
    private javax.swing.JLabel labelMovieNumberUser;
    private javax.swing.JLabel labelTargetUser;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTitle1;
    private javax.swing.JLabel labelUserNumberRating;
    private javax.swing.JLabel labelUserNumberUser;
    private javax.swing.JPanel panelByCustomRating;
    private javax.swing.JPanel panelByTargetUser;
    private javax.swing.JTextField txtMovieNumberRating;
    private javax.swing.JTextField txtMovieNumberUser;
    private javax.swing.JTextField txtRating1;
    private javax.swing.JTextField txtRating2;
    private javax.swing.JTextField txtRating3;
    private javax.swing.JTextField txtRating4;
    private javax.swing.JTextField txtRating5;
    private javax.swing.JTextArea txtResultsRating;
    private javax.swing.JTextArea txtResultsUser;
    private javax.swing.JTextField txtUserNumberRating;
    private javax.swing.JTextField txtUserNumberUser;
    // End of variables declaration//GEN-END:variables
}
